const NO_USER_FOUND = 'NO_USER_FOUND';
const ERROR_IN_QUERY = 'ERROR_IN_QUERY';
const USER_ADDED = 'USER_ADDED';
const ERROR_DURING_INSERT = 'ERROR_DURING_INSERT';
const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';
const ERROR_UPDATING_DETAILS = 'ERROR_UPDATING_DETAILS';
const UPDATED_DETAILS = 'UPDATED_DETAILS';
module.exports={
  NO_USER_FOUND,
  ERROR_IN_QUERY,
  USER_ADDED,
  ERROR_DURING_INSERT,
  USER_ALREADY_EXISTS
}